### PR TITLE
New identifier pattern

### LINKED ISSUE #63: New identifier pattern
Soon my pull request at https://github.com/PebbleTemplates/pebble/pull/544 will be merged so the identifier regex will need to be changed to `[\\p{IsLetter}_][\\p{IsLetter}\\p{IsDigit}_]*`. I hope that `\\p{...}` is usable in ANTLR.

### PR DESCRIPTION
**Pull request by objectProgrammer**
Fixes #63 

Untested.

### CODE REVIEW

**Comment by objectProgrammer** [comment]
@bjansen Any reason for not merging?

**Comment by bjansen** [comment]
I see two problems: 
* `\\p` should be escaped only once (`\p`)
* `\p{IsLetter}` seems to be a Java thing, which maps to multiple Unicode things (see the Javadoc of `java.lang.Character#isLetter(int)`). [ANTLR only works with Unicode properties](https://github.com/antlr/antlr4/blob/master/doc/lexer-rules.md#lexer-rule-elements), so when I build the project I get these warnings:
```
warning(156): com/github/bjansen/pebble/parser/PebbleLexer.g4:277:6: invalid escape sequence \p{IsLetter}
warning(156): com/github/bjansen/pebble/parser/PebbleLexer.g4:277:21: invalid escape sequence \p{IsLetter}
```

Same thing for `\p{IsDigit}`, but this one is easier: it looks like it should be `\p{Nd}` or `\p{Decimal_Number}`.

**Comment by bjansen** [comment]
Ah, it seems that `\p{IsLetter}` should be `\p{Letter}`:


Abbr | Long | Description
-- | -- | --
Lu | Uppercase_Letter | an uppercase letter
Ll | Lowercase_Letter | a lowercase letter
Lt | Titlecase_Letter | a digraphic character, with first part uppercase
LC | Cased_Letter | Lu \| Ll \| Lt
Lm | Modifier_Letter | a modifier letter
Lo | Other_Letter | other letters, including syllables and ideographs
L | Letter | Lu \| Ll \| Lt \| Lm \| Lo

**Comment by objectProgrammer** [comment]
Apologies, it's a habit from Java to always use \\. I'll fix that and IsLetter -> Letter now.

**Comment by bjansen** [comment]
OK it works correctly now. Thanks for the PR!

**Comment by objectProgrammer** [comment]
No problem, but I think you clicked close instead of merge by mistake.

**Comment by bjansen** [comment]
😱

**Pull request merged**
